[package]
name = "bookmark-directory"
version = "0.1.0"
authors = ["Luku <luku.3659@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite"] }
prettytable-rs = "0.8.0"
dotenv = "0.15.0"
structopt = "0.3.21"
colored = "2.0.0"
